# 监听端口
bind [::]:5053 -no-rule-addr -no-rule-nameserver -no-dualstack-selection -force-aaaa-soa -no-speed-check -no-cache

log-level info
log-file /tmp/smartdns/smartdns.log

cache-persist yes
cache-file /tmp/smartdns/cache.dump

dualstack-ip-selection no
force-AAAA-SOA yes
response-mode fastest-response
force-qtype-SOA 65
tcp-idle-time 120

# Global
server-tls 8.8.8.8:853
server-tls 8.8.4.4:853
server-tls 1.1.1.1:853
server-tls 1.0.0.1:853
server-tls 185.222.222.222:853
server-tls 9.9.9.11:853
