spring:
  application:
    name: adg-rule
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  rule:
    remote:
    #Adguard基础规则
      - 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt'  #AdGuard Base filter
      - 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_224_Chinese/filter.txt' #AdGuard Chinese filter
      - 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/MobileFilter/sections/adservers.txt' #AdGuard Mobile Ads filter
      - 'https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt' #AdGuard DNS filter
      - 'https://raw.githubusercontent.com/AdguardTeam/HostlistsRegistry/refs/heads/main/filters/other/filter_7_SmartTVBlocklist/filter.txt' #SmartTV

    #自用添加
      - 'https://anti-ad.net/easylist.txt' #name: anti-AD
      - 'https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt' #name: StevenBlack/hosts规则
      - 'https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/combined_disguised_trackers.txt' #AWAvenue Ads Rule
      - 'https://cdn.jsdelivr.net/gh/sbwml/halflife-list@master/ad.txt' #name: HalfLife
      - 'https://raw.githubusercontent.com/afwfv/DD-AD/refs/heads/release/easylist.txt' #name: DD-AD
      - 'https://raw.githubusercontent.com/rssvcn/qy-Ads-Rule/main/black.txt' #name: 晴雅广告拦截规则
      - 'https://raw.githubusercontent.com/damengzhu/banad/main/jiekouAD.txt' #name: jiekouAD
      - 'https://raw.githubusercontent.com/2Gardon/SM-Ad-FuckU-hosts/master/SMAdHosts' #name: SMAdHosts
      - 'https://raw.githubusercontent.com/qq5460168/666/refs/heads/master/rules.txt' #name: 那个谁520规则
      - 'https://raw.githubusercontent.com/TTDNS/Cat/refs/heads/main/DNS.TXT' #name: TTDNS
      - 'https://raw.githubusercontent.com/Kuroba-Sayuki/FuLing-AdRules/Master/FuLingRules/FuLingBlockList.txt' #name: 茯苓广告规则
      - 'https://raw.githubusercontent.com/2771936993/HG/main/hg1.txt' #name: HG

    #隐私保护
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_67.txt' #name: HaGeZi's Apple Tracker Blocklist
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_60.txt' #name: HaGeZi's Xiaomi Tracker Blocklist
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_65.txt' #name: HaGeZi's Vivo Tracker Blocklist
      - 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_61.txt' #name: HaGeZi's Samsung Tracker Blocklist
      - 'https://raw.githubusercontent.com/AdguardTeam/HostlistsRegistry/refs/heads/main/filters/other/filter_66_HageziOppoRealmeTrackerBlocklist/filter.txt' #name: HaGeZi's OPPO & Realme Tracker Blocklist

    #白名单规则
      - 'https://raw.githubusercontent.com/Kuroba-Sayuki/FuLing-AdRules/Master/FuLingRules/FuLingAllowList.txt' #name: 茯苓允许列表
      - 'https://raw.githubusercontent.com/afwfv/DD-AD/refs/heads/release/DD-AD.txt' #name: DD-AD允许列表
      - 'https://raw.githubusercontent.com/qq5460168/666/master/allow.txt' #name: 那个谁520广告白名单
      
    #本地规则
    local: #本地规则请将文件移动到项目路径rule目录中
      - 'mylist.txt'
      
  output:
    path: rule                              #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt:                              #输出文件名
        - DNS_EXCEPTION                     #AdGuard Home例外规则
        - DNS_FILTER                        #规范域名拦截规则
        - HOSTS                             #Hosts规则
        - REGEX                             #严格正则规则，AdGH支持
        - MODIFY                            #AdGuard客户端专用规则
      adgh.txt:
        - DNS_FILTER 
        - REGEX      
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DNS_EXCEPTION
        - DNS_FILTER
      modify.txt:
        - MODIFY
      allow.txt:                            #单独输出的白名单/放行规则（@@||domain^）
        - DNS_EXCEPTION
